  kafka:
    image: confluentinc/cp-kafka:4.0.2
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_JMX_PORT=9999
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafka_network
    ports:
      - 9092:9092
      - 9999:9999
    restart: unless-stopped

 kafka-manager:
    image: sheepkiller/kafka-manager:alpine
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    environment:
      - ZK_HOSTS=zookeeper:2181
      - KM_ARGS=-Dhttp.port=9001
    ports:
      - 9001:9001
    restart: unless-stopped

